title = "oro-jackson"

[settings]
logging = true

[server]
port = "8080"

[plugins.transformers]
markdown = { enable = true }
sanitize = { enable = true }
frontmatter = { enable = true }

[plugins.emitters]
static_assets = { enable = true }
file_page = { enable = true }
folder_page = { enable = true, show_folder_page_children = true }

[theme.light]
color_base_100 = "oklch(98% 0 0)"
color_base_200 = "oklch(97% 0 0)"
color_base_300 = "oklch(92% 0 0)"
color_base_content = "oklch(20% 0 0)"
color_primary = "oklch(77% 0.152 181.912)"
color_primary_content = "oklch(27% 0.046 192.524)"
color_secondary = "oklch(70% 0.015 286.067)"
color_secondary_content = "oklch(14% 0.005 285.823)"
color_accent = "oklch(71% 0.202 349.761)"
color_accent_content = "oklch(28% 0.109 3.907)"
color_neutral = "oklch(14% 0 0)"
color_neutral_content = "oklch(98% 0 0)"
color_info = "oklch(58% 0.158 241.966)"
color_info_content = "oklch(97% 0.013 236.62)"
color_success = "oklch(59% 0.145 163.225)"
color_success_content = "oklch(97% 0.021 166.113)"
color_warning = "oklch(64% 0.222 41.116)"
color_warning_content = "oklch(98% 0.016 73.684)"
color_error = "oklch(57% 0.245 27.325)"
color_error_content = "oklch(97% 0.013 17.38)"
radius_selector = "1rem"
radius_field = "1rem"
radius_box = "1rem"
size_selector = "0.25rem"
size_field = "0.25rem"
border = "1px"
depth = "0"
noise = "0"

[theme.dark]
color_base_100 = "oklch(14% 0.005 285.823)"
color_base_200 = "oklch(21% 0.006 285.885)"
color_base_300 = "oklch(27% 0.006 286.033)"
color_base_content = "oklch(96% 0.001 286.375)"
color_primary = "oklch(77% 0.152 181.912)"
color_primary_content = "oklch(27% 0.046 192.524)"
color_secondary = "oklch(70% 0.015 286.067)"
color_secondary_content = "oklch(14% 0.005 285.823)"
color_accent = "oklch(71% 0.202 349.761)"
color_accent_content = "oklch(28% 0.109 3.907)"
color_neutral = "oklch(37% 0.013 285.805)"
color_neutral_content = "oklch(98% 0 0)"
color_info = "oklch(58% 0.158 241.966)"
color_info_content = "oklch(97% 0.013 236.62)"
color_success = "oklch(59% 0.145 163.225)"
color_success_content = "oklch(97% 0.021 166.113)"
color_warning = "oklch(64% 0.222 41.116)"
color_warning_content = "oklch(98% 0.016 73.684)"
color_error = "oklch(57% 0.245 27.325)"
color_error_content = "oklch(97% 0.013 17.38)"
radius_selector = "1rem"
radius_field = "1rem"
radius_box = "1rem"
size_selector = "0.25rem"
size_field = "0.25rem"
border = "1px"
depth = "0"
noise = "0"
