[plugins.transformers]
markdown = { enable = true }

[plugins.emitters]
folder_page = { enable = true, show_folder_page_children = true }
file_page = { enable = true }
static_assets = { enable = true }

[theme]
radius = "2rem"

[theme.light]
background = "#ebfdfe"
foreground = "#0d4c62"
primary = "#fca4d4"
secondary = "#ffb667"
accent = "#71d1fe"
neutral = "#0090b5"

[theme.dark]
background = "#ebfdfe"
foreground = "#0d4c62"
primary = "#fca4d4"
secondary = "#ffb667"
accent = "#71d1fe"
neutral = "#0090b5"
