version: "3"
interval: 500ms
dotenv: [".env"]
tasks:
  # serve the content
  serve:
    cmds:
      - cargo run serve --content ../bookshelf/content {{.CLI_ARGS}}
  # build the content
  build:
    cmds:
      - cargo run build --content ../bookshelf/content --output ./build {{.CLI_ARGS}}
  # run tests
  test:
    cmds:
      - cargo test -- --nocapture {{.CLI_ARGS}}
